config/routes.rb
Rails.application.routes.draw do
  

  root to: 'items#index'
  
  resources :items do
    collection do
      get "category_find"
    end
    member do
      get "purchase1"
      post 'pay'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'logging_in'
      get 'user_add'
      get 'phone_add'
      get 'address_add'
      get 'card_add'
      get 'complete'
    end
    member do
      get "signout"
      get "card"
      get "profile"
      post "logging_off"
      get 'identification'
      get "my_selling_items"
    end
  end

  resources :creditcard, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcard#show'
      post 'pay', to: 'creditcard#pay'
      post 'pay_second', to: 'creditcard#pay_second'
      post 'pay_third', to: 'creditcard#pay_third'
      post 'delete', to: 'creditcard#delete'
    end
    member do
      get "card"
      get "registrationcard"
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
    end
    member do
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/controllers/creditcard_controller.rb
class CreditcardController < ApplicationController

  require "payjp"

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Creditcard.new(user_id: @current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to complete_users_path
      else
        redirect_to new_creditcard_path
      end
  end

  def pay_second #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Creditcard.new(user_id: @current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_creditcard_path(@current_user.id)
      else
      end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Creditcard.where(user_id: @current_user.id).first
    if card.blank?
      redirect_to root_path
    else
      Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to card_creditcard_path(@current_user.id)
  end


  def card
    card = Creditcard.where(user_id: @current_user.id).first
    if card.blank?
    else
      Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
 
end

app/helpers/creditcard_helper.rb
module CreditcardHelper
end

app/views/creditcard/card.html.haml
.wrapper 
  .hedder
    = render "items/hedder"
    = render "layouts/pankuzu"
    .main
      .content2
        .pay-info
          .pay-info__text
            %p 支払い方法
          .pay-info__cards-info
            .bottom-border
              %section.cards-list
                .cards-list__text
                  %p クレジットカード一覧
                .cards-list__info
                - if @default_card_information.blank?
                  -# = form_tag(creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                  = link_to creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm" do
                    %button.credit_btn 登録する    
                - else
                  = "**** **** **** " + @default_card_information.last4
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
                  %section
                    .cards-list__info
                    = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912",width: "49",alt:"visa",height:"15")
                    = form_tag(delete_creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                      %button.credit_btn 削除する           
            .about-pay
              %span 支払い方法について
              = fa_icon "angle-right"
        = render "users/l-side"  
.footer
  = render 'items/footer'           



       

app/views/creditcard/registrationcard.haml
= render "items/header"
.main
  .main__header5
    支払い方法
  = form_tag(pay_third_creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm",class: "main__card") do
    %label{for: "inputCardNumber"} カード番号
    %span 必須
    = text_field_tag "number", "", class: 'main__card__number', placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2356214421",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2356214421",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2356214421",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2356214421",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2356214421",width: "49",alt:"visa",height:"15")
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2356214421",width: "49",alt:"visa",height:"15")
    .deadline
      %label{for: "inputExp"} 有効期限
      %span 必須
    %select#exp_month{name: "exp_month", type: "text"}
      %option{value: ""} --
      %option{value: "1"}01
      %option{value: "2"}02
      %option{value: "3"}03
      %option{value: "4"}04
      %option{value: "5"}05
      %option{value: "6"}06
      %option{value: "7"}07
      %option{value: "8"}08
      %option{value: "9"}09
      %option{value: "10"}10
      %option{value: "11"}11
      %option{value: "12"}12
    月
    %select#exp_year{name: "exp_year", type: "text"}
      %option{value: ""} --
      %option{value: "2019"}19
      %option{value: "2020"}20
      %option{value: "2021"}21
      %option{value: "2022"}22
      %option{value: "2023"}23
      %option{value: "2024"}24
      %option{value: "2025"}25
      %option{value: "2026"}26
      %option{value: "2027"}27
      %option{value: "2028"}28
      %option{value: "2029"}29
    年
    %br
    .main__card__security-label
    %label{for: "inputCVC"} CVC/セキュリティコード
    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
    #card_token
    = submit_tag "追加する", id: "token", class: 'main__card__btn'
= render "items/footer2"

app/views/creditcard/show.html.haml
.wrapper
  .hedder
    = render "items/hedder" 
    .main
      .content
        .content__right
          .main__header5
            支払い方法
          = form_tag(pay_second_creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm",class: "main__card") do
            %label{for: "inputCardNumber"} カード番号
            %span 必須
            = text_field_tag "number", "", class: 'main__card__number', placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2356214421",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2356214421",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2356214421",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2356214421",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2356214421",width: "49",alt:"visa",height:"15")
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2356214421",width: "49",alt:"visa",height:"15")
            .deadline
              %label{for:"inputExp"} 有効期限
              %span 必須
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            月
            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            年
            %br
            .main__card__security-label
            %label{for: "inputCVC"} CVC/セキュリティコード
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            #card_token
            = submit_tag "追加する", id: "token", class: 'main__card__btn'
        = render "users/l-side"  
    .footer
      = render 'items/footer'  