config/routes.rb
Rails.application.routes.draw do
  

  root to: 'items#index'
  
  resources :items do
    collection do
      get "category_find"
    end
    member do
      get "purchase1"
      post 'pay'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'logging_in'
      get 'user_add'
      get 'phone_add'
      get 'address_add'
      get 'card_add'
      get 'complete'
    end
    member do
      get "signout"
      get "card"
      get "profile"
      post "logging_off"
      get 'identification'
      get "my_selling_items"
    end
  end

  resources :creditcard, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcard#show'
      post 'pay', to: 'creditcard#pay'
      post 'pay_second', to: 'creditcard#pay_second'
      post 'pay_third', to: 'creditcard#pay_third'
      post 'delete', to: 'creditcard#delete'
    end
    member do
      get "card"
      get "registrationcard"
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
    end
    member do
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :likes
  has_many :items, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  has_one :card, dependent: :destroy
  accepts_nested_attributes_for :card

  zenkaku = /\A[ぁ-んァ-ン一-龥]+\z/
  kana = /\A([ァ-ン]|ー)+\z/
  pass = /\A[a-z\d]{7,100}\z/i
  email = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  phone = /\A\d{10,11}\z/


  validates :nickname, presence: true, length: { maximum: 20 }
  validates :password, format: { with: pass }, presence: true
  validates :first_name, presence: true, length: { maximum: 15 }, format: { with: zenkaku }
  validates :last_name, presence: true, length: { maximum: 15 }, format: { with: zenkaku }
  validates :first_name_kana, presence: true, length: { maximum: 15 }, format: { with: kana }
  validates :last_name_kana, presence: true, length: { maximum: 15 }, format: { with: kana }
  validates :birthday, presence: true
  validates :phone_number, format: { with: phone }, presence: true
  validates :email, uniqueness: true, format: { with: email }, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action:set_session, only: :create

  def my_selling_items
    user = User.find_by(id: session[:user_id])
    @my_items = user.items.order("created_at DESC")
  end

  def show
    @user = User.find_by(id: session[:user_id])
  end


  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(nickname: params[:nickname])
    redirect_to("/")
  end


  def signout
  end

  def logging_off
    session[:user_id] = nil
    redirect_to root_path
  end

  def card
  end
  

  def login
    @user = User.new
  end

  def logging_in
    @user = User.find_by(email: user_params[:email])
    if verify_recaptcha(model: @user)
      if @user && @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        flash[:notice] = "ログインしました"
        redirect_to("/items")
      else
        flash[:alert] = "メールアドレスまたはパスワードが間違っています"
        redirect_to("/users/login")
      end
    else
      flash[:alert] = "「私はロボットではありません」にチェックを入れてください"
      redirect_to("/users/login")
    end
  end

  def user_add
    @user = User.new
  end

  def phone_add
    if params[:user]
      session[:nickname] = user_params[:nickname]
      session[:email] = user_params[:email]
      session[:password] = user_params[:password]
      session[:last_name] = user_params[:last_name]
      session[:first_name] = user_params[:first_name]
      session[:last_name_kana] = user_params[:last_name_kana]
      session[:first_name_kana] = user_params[:first_name_kana]
      session[:birthday] = birthday_join
    end
    @user = User.new
    if verify_recaptcha(model: @user) == false && params[:user]
      redirect_to action: "user_add"
      flash[:alert] = "「私はロボットではありません」にチェックを入れてください"
    end
  end

  def address_add
    if params[:user]
      session[:phone_number] = user_params[:phone_number]
    end
    user_is_valid
    @user = User.new
    @user.build_address
  end

  def card_add
    @user = User.new
    card = User.where(user_id: @current_user.id)
  end

  def create
    address_is_valid and return
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthday: session[:birthday],
      phone_number: session[:phone_number]
      
    )
    @user.build_address(
      post_number: session[:post_number],
      prefecture: session[:prefecture],
      city: session[:city],
      address: session[:address],
      building: session[:building]
    )
    
    if @user.save
      session.clear
      session[:user_id] = @user.id
      redirect_to action: 'card_add'
    else
      session.clear
      flash[:alert] = "入力をもう一度やり直してください"
      redirect_to action: 'user_add'
    end
  end

  def complete
  end

  def identification
    @current_user = User.find_by(id: session[:user_id])
    @user = User.new
    @user.build_address
  end

  
  def birthday_join
    date = params[:birthday]
    
    if date["birthday(1i)"].empty? || date["birthday(2i)"].empty? || date["birthday(3i)"].empty?
      return
    end
    
    Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i
  end
  
  def card_expiry_join
    date = card_params[:card_attributes]
    
    if date["expiry_date(1i)"].empty? || date["expiry_date(2i)"].empty? || date["expiry_date(3i)"].empty?
      return
    end
    
    Date.new date["expiry_date(1i)"].to_i,date["expiry_date(2i)"].to_i,date["expiry_date(3i)"].to_i
  end
  
  def user_is_valid
    
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthday: session[:birthday],
      phone_number: session[:phone_number]
    )
    if @user.valid?
    else
      i = 0
      @user.errors.full_messages.each do |message|
        key_st = "alert" + "#{i}"
        key = key_st.to_sym
        flash[key] = message
        i += 1
      end
      redirect_to action: "user_add"
    end
  end
  
  def address_is_valid
    
    @address = Address.new(
      post_number: session[:post_number],
        prefecture: session[:prefecture],
        city: session[:city],
        address: session[:address],
        building: session[:building]
      )
      if @address.valid?
        return false
      else
        i = 0
        @address.errors.full_messages.each do |message|
          key_st = "alert" + "#{i}"
          key = key_st.to_sym
          flash[key] = message
          i += 1
        end
        redirect_to action: 'address_add'
        return true
      end
    end
    
    def set_session
      session[:post_number] = address_params[:address_attributes][:post_number]
      session[:prefecture] = address_params[:address_attributes][:prefecture]
      session[:city] = address_params[:address_attributes][:city]
      session[:address] = address_params[:address_attributes][:address]
      session[:building] = address_params[:address_attributes][:building]
    end
    
    
    def card
      @item = Item.find(params[:id]) 
      card = Creditcard.where(user_id: @current_user.id).first
      if card.blank?
        redirect_to root_path
      else
        Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)
        redirect_to root_path
      end
    end
    
    
    
  end
  
  private 
    def user_params
      params.require(:user).permit(
        :nickname, :email, :password, :last_name, :first_name,
        :last_name_kana, :first_name_kana, :phone_number)
    end

    def address_params
      params.require(:user).permit(
        address_attributes: [:id, :post_number, :prefecture,
          :city, :address, :building])
    end

    def card_params
      params.require(:user).permit(
        card_attributes: [:id, :card_number, "expiry_date(1i)",
         "expiry_date(2i)", "expiry_date(3i)", :security_code])
    end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_l-side.html.haml
.content__left
  %ul
    %li
      = link_to user_path(@current_user.id) do
        マイページ
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        お知らせ
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        いいね！一覧        
        = fa_icon 'angle-right'
    %li
      = link_to ""do
        出品する
        = fa_icon 'angle-right'
    %li
      = link_to my_selling_items_user_path(@current_user.id) do
        出品した商品---出品中
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        出品した商品---取引中
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        出品した商品---売却済
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        購入した商品---取引中
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        購入した商品---過去の取引
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        ニュース一覧
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        評価一覧
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        ガイド
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        お問い合わせ
        = fa_icon 'angle-right'
  %h3 メルペイ
  %ul
    %li
      = link_to "" do
        売上・振込申請
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        ポイント
        = fa_icon 'angle-right'
  %h3 設定
  %ul
    %li
      = link_to   edit_user_path(@current_user.id) do
        プロフィール
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        住所変更
        = fa_icon 'angle-right'
    %li
      = link_to card_creditcard_path(@current_user.id) do
        支払い方法
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        メール/パスワード
        = fa_icon 'angle-right'
    %li
      = link_to identification_user_path(id: session[:user_id]) do
        本人情報
        = fa_icon 'angle-right'
    %li
      = link_to "" do
        電話番号の確認
        = fa_icon 'angle-right'
    %li
      = link_to signout_user_path(@current_user.id) do
        ログアウト
        = fa_icon 'angle-right'

app/views/users/_myitem.html.haml
= link_to item_path(myitem), {data: {"turbolinks": false}} do
  .one_item
    - if myitem.images.attached?
      = image_tag myitem.images.last, class:'item_image'
      .one_item_title
        = myitem.name
      .selling_now 出品中
    = fa_icon 'chevron-right'
  

app/views/users/address_add.html.haml
.container-k
  = render partial: 'layouts/shared/header-with-progress'

  .main-k
    .main-k__header4
      発送元・お届け先住所入力
    = form_for @user, url: users_path, method: :post, html: {class: "main-k__address"} do |f|
      = f.fields_for :address do |d|
        = d.label '郵便番号'
        %span 必須
        = d.text_field :post_number, class: 'main-k__address__postal-code', placeholder: '例）123-4567'
        = d.label '都道府県'
        %span 必須
        = d.select :prefecture, Address.prefectures.keys
        = d.label '市区町村'
        %span 必須
        = d.text_field :city, class: 'main-k__address__city', placeholder: '例）横浜市緑区'
        = d.label '番地'
        %span 必須
        = d.text_field :address, class: 'main-k__address__banchi', placeholder: '例）青山1-1-1'
        = d.label '建物名'
        %span.gray 任意
        = d.text_field :building, class: 'main-k__address__building', placeholder: '例）柳ビル103'
      = f.submit '次へ進む', class: 'main-k__address__btn'

  = render partial: 'layouts/shared/footer'

app/views/users/card_add.html.haml
.container-k
  = render partial: 'layouts/shared/header-with-progress'
  .main
    .main__header5
      支払い方法
    = form_tag(pay_creditcard_index_path, method: :post, id: 'charge-form',  name: "inputForm",class: "main__card") do
      %label{for: "inputCardNumber"} カード番号
      %span 必須
      = text_field_tag "number", "", class: 'main__card__number', placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2356214421",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2356214421",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2356214421",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2356214421",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2356214421",width: "49",alt:"visa",height:"15")
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2356214421",width: "49",alt:"visa",height:"15")
      .deadline
        %label{for: "inputExp"} 有効期限
        %span 必須
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      月
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2019"}19
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      年
      %br
      .main__card__security-label
      %label{:for => "inputCVC"} CVC/セキュリティコード
      %span 必須
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "追加する", id: "token", class: 'main__card__btn'
  = render partial: 'layouts/shared/footer'

app/views/users/complete.html.haml
.container-k
  = render partial: 'layouts/shared/header-with-progress'

  .main-k
    .main-k__header6
      会員登録完了
    .main-k__body
      .main-k__body__finish-message
        ありがとうございます。会員登録が完了しました。
      = link_to root_path, {data: {"turbolinks": false}} do
        .main-k__body__start-btn
          メルカリをはじめる

  = render partial: 'layouts/shared/footer'

app/views/users/edit.html.haml
- if session[:user_id]
  .wrapper
    .hedder
      = render "items/hedder"
      = render "layouts/pankuzu"
      .main
        .content2
          .content2__right
            .title
              プロフィール
            = form_with url: items_path, method: :post, id: 'form', html: { name: "inputForm" } do |f|
              .form2
                %figure
                  = image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png", size: "60x60")
                  = f.text_field :nickname, type: 'text', class: 'namechange', maxlength: "16"
              .form3
                = f.text_area  :profile, type: 'text', class: 'profilechange', placeholder: '例）こんにちは☆ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心出品しています。服のサイズは主に９号です。気持ちよく取引できるように心がけていますので、商品や発送方法どご質問がありましたらお気軽にどうぞ♪'
              .form4
                = f.submit '変更する',  class: 'submit'
          = render "l-side"  
      .footer
        = render 'items/footer'            
            

app/views/users/identification.html.haml
.wrapper
  .hedder
    = render "items/hedder"
    = render "layouts/pankuzu"

  .main
    .content
      .content__right
        .title
          本人情報の登録
        .form
          .text-box
            .form-text
              お客さまの本人情報をご登録ください。
              %br
                登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            .about
              =link_to "", class: "about-link" do
                本人確認書類のアップロードについて
                %i.fas.fa-chevron-right
          .form-group
            %label
              お名前
            %p
              = @current_user.last_name
              = @current_user.first_name
          .form-group
            %label
              お名前カナ
            %p
              = @current_user.last_name_kana
              = @current_user.first_name_kana
          .form-group
            %label
              生年月日
            %p
              = @current_user.birthday
          = form_for @user, url: card_add_users_path, method: :get, html: {class: "form-group"} do |f|
            = f.fields_for :address do |d|
              = d.label '郵便番号'
              %span.form-arbitrary 任意
              = d.text_field :post_number, class: 'postal-code', placeholder: '例）123-4567'
              = d.label '都道府県'
              %span.form-arbitrary 任意
              = d.select :prefecture, Address.prefectures.keys
              = d.label '市区町村'
              %span.form-arbitrary 任意
              = d.text_field :city, class: 'city', placeholder: '例）横浜市緑区'
              = d.label '番地'
              %span.form-arbitrary 任意              
              = d.text_field :address, class: 'banchi', placeholder: '例）青山1-1-1'
              = d.label '建物名'
              %span.form-arbitrary 任意
              = d.text_field :building, class: 'building', placeholder: '例）柳ビル103'
            = f.submit '次へ進む', class: 'btn'
          .about
            =link_to "", class: "about-link" do
              本人確認書類のアップロードについて
              %i.fas.fa-chevron-right

      = render "l-side"   

  .footer
    = render 'items/footer'   

app/views/users/login.html.haml
.container-k
  = render partial: 'layouts/shared/header'

  .main-k
    .main-k__no-account
      %p.main-k__no-account__text
        アカウントをお持ちでない方はこちら
      = link_to user_add_users_path, {data: {"turbolinks": false}} do
        .main-k__no-account__btn
          新規会員登録
    .main-k__sns-login
      = link_to 'Facebook', {data: {"turbolinks": false}} do
        .main-k__sns-login__facebook
          = fa_icon 'facebook-square'
          Facebookでログイン
      = link_to 'Google', {data: {"turbolinks": false}} do
        .main-k__sns-login__google
          = fa_icon 'google'
          Googleでログイン
    = form_for @user, url: logging_in_users_path, method: :post, html: {class: "main-k__email-pass-form"} do |f|
      = f.email_field :email, class: 'main-k__email-pass-form__email', placeholder: 'メールアドレス'
      = f.password_field :password, class: 'main-k__email-pass-form__password', placeholder: 'パスワード'
      = recaptcha_tags
      = f.submit 'ログイン', class: 'main-k__email-pass-form__btn'
      .main-k__email-pass-form__forgot-password
        パスワードをお忘れの方
        
  = render partial: 'layouts/shared/footer'

app/views/users/my_selling_items.html.haml
.wrapper
  .hedder
    = render "items/hedder"
    = render "layouts/pankuzu"
  - if session[:user_id]
    .main
      .content
        .content__right
          %h2.mypage-tab-head 出品した商品
          %ul.listing-tabs
            %li.three_boxes_first
              %h3
                %a.selling_now 出品中
            %li.three_boxes
              %h3
                %a.selling_now 取引中
            %li.three_boxes
              %h3
                %a.selling_now 売却済み
          = render partial: 'myitem', collection: @my_items



        = render "l-side"   




  .footer
    = render 'items/footer'

app/views/users/new.html.haml
.container-k
  = render partial: 'layouts/shared/header'

  .main-k
    .main-k__header
      新規会員登録
    .main-k__how-to-register
      = link_to user_add_users_path, {data: {"turbolinks": false}} do
        .main-k__how-to-register__email
          = fa_icon 'envelope'
          メールアドレスで登録する
      = link_to 'facebook', {data: {"turbolinks": false}} do
        .main-k__how-to-register__facebook
          = fa_icon 'facebook-square'
          facebookで登録する
      = link_to 'google', {data: {"turbolinks": false}} do
        .main-k__how-to-register__google
          = fa_icon 'google'
          googleで登録する

  = render partial: 'layouts/shared/footer'

app/views/users/phone_add.html.haml
.container-k
  = render partial: 'layouts/shared/header-with-progress'

  .main-k
    .main-k__header3
      電話番号の確認
    = form_for @user, url: address_add_users_path, method: :get, html: {class: "main-k__phone-form"} do |f|
      = f.label '携帯電話の番号'
      = f.telephone_field :phone_number, class: 'main-k__phone-form__number', placeholder: '例）09012345678'
      .main-k__phone-form__conf-notice
        本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して
        認証を行う事があります。
      = f.submit '次へ進む', class: 'main-k__phone-form__btn'
      .main-k__phone-form__privacy-message
        ※電話番号は本人確認や不正利用防止のために利用します。
        他のユーザーに公開されることはありません。
      .main-k__phone-form__reason-message
        電話番号の確認が必要な理由
        = fa_icon 'chevron-right'
  = render partial: 'layouts/shared/footer'

app/views/users/show.html.haml
.wrapper
  .hedder
    = render "items/hedder"
    = render "layouts/pankuzu"
  - if session[:user_id]
    .main
      .content
        .content__right
          .content__right--top
            .mypageicon
              = link_to "#" do
                %figure
                  = image_tag("https://static.mercdn.net/images/member_photo_noimage_thumb.png", size: "60x60")
                %h2 
                  = @current_user.nickname
              %ul.mypageicon__num
                %li
                  評価
                  0
                %li
                  出品数
                  0
            %ul.mypagetabs
              %li.mypagetab お知らせ
              %li.mypagetab やることリスト
            .panel-group
            .tabcontent
              %ul
                %li
                %li
                %li
                %li
                  = link_to "一覧を見る", "#", class: "mypageBtn"
            .tabcontent
              %ul
                %li
                %li
                %li
                %li
                  = link_to "一覧を見る", "#", class: "mypageBtn"
          .content__right--bottom
            %h4 購入した商品
            %ul.mypagetabs2  
              %li.mypagetab2 お知らせ
              %li.mypagetab2 やることリスト
            .tabcontent2
              %ul
                %li
                %li
                %li
                %li
                  = link_to "一覧を見る", "#", class: "mypageBtn"
            .tabcontent2
              %ul
                %li
                %li
                %li
                %li
                  = link_to "一覧を見る", "#", class: "mypageBtn"
        = render "l-side"   
  .footer
    = render 'items/footer'

app/views/users/signout.html.haml
- if session[:user_id]
  .wrapper
    .hedder
      = render "items/hedder"
      = render "layouts/pankuzu" 
    .main
      .content2
        .signout
          .signout__container
            .signout__container__back
              = link_to logging_off_user_path, method: :post do
                %button.back-btn ログアウト
        = render "l-side"  
    .footer
      = render 'items/footer'

app/views/users/user_add.html.haml
.container-k
  = render partial: 'layouts/shared/header-with-progress'
  .main-k
    .main-k__header2
      会員情報入力
    = form_for @user, url: phone_add_users_path, method: :get, html: {class: "main-k__form"} do |f|
      = f.label 'ニックネーム'
      %span 必須
      = f.text_field :nickname, class: 'main-k__form__nickname', placeholder: '例）メルカリ太郎'
      = f.label 'メールアドレス'
      %span 必須
      = f.email_field :email, class: 'main-k__form__email', placeholder: 'PC・携帯どちらでも可'
      = f.label 'パスワード'
      %span 必須
      = f.password_field :password, class: 'main-k__form__password', placeholder: '７文字以上'
      = check_box_tag 'main-k__form__checkbox'
      = label_tag "パスワードを表示する"
      .main-k__form__reveal-pass
      .main-k__form__auth-text
        %h3.main-k__form__auth-text__sub 本人確認
        %p.main-k__form__auth-text__text
          安心・安全にご利用いただくために、お客様の本人情報の登録にご協力ください。
          他のお客様に公開されることはありません。
      .main-k__form__kanji-label
        = f.label 'お名前（全角）'
        %span 必須
      = f.text_field :last_name, class: 'main-k__form__kanji-familyname', placeholder: '例）山田'
      = f.text_field :first_name, class: 'main-k__form__kanji-firstname', placeholder: '例）綾'
      .main-k__form__kana-label
        = f.label 'お名前カナ（全角）'
        %span 必須
      = f.text_field :last_name_kana, class: 'main-k__form__kana-familyname', placeholder: '例）ヤマダ'
      = f.text_field :first_name_kana, class: 'main-k__form__kana-firstname', placeholder: '例）アヤ'
      .main-k__form__birthday-label
        = f.label '生年月日'
        %span 必須
      != sprintf(f.date_select(:birthday, prefix:'birthday',
      with_css_classes:'test',prompt:"--",use_month_numbers:true,
      start_year:Time.now.year, end_year:1900, date_separator:'%s'),'年','月')+'日'
      .main-k__form__be-collect-info
        ※本人情報は正しく入力してください。会員登録後、修正するには
        お時間をいただく場合があります。
      = recaptcha_tags
      .main-k__form__conf-message
        「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします
      = f.submit '次へ進む', class: 'main-k__form__btn'
      .main-k__form__register-message
        本人情報の登録について
        = fa_icon 'chevron-right'

  = render partial: 'layouts/shared/footer'