config/routes.rb
Rails.application.routes.draw do
  

  root to: 'items#index'
  
  resources :items do
    collection do
      get "category_find"
    end
    member do
      get "purchase1"
      post 'pay'
    end
  end

  resources :users do
    collection do
      get 'login'
      post 'logging_in'
      get 'user_add'
      get 'phone_add'
      get 'address_add'
      get 'card_add'
      get 'complete'
    end
    member do
      get "signout"
      get "card"
      get "profile"
      post "logging_off"
      get 'identification'
      get "my_selling_items"
    end
  end

  resources :creditcard, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcard#show'
      post 'pay', to: 'creditcard#pay'
      post 'pay_second', to: 'creditcard#pay_second'
      post 'pay_third', to: 'creditcard#pay_third'
      post 'delete', to: 'creditcard#delete'
    end
    member do
      get "card"
      get "registrationcard"
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
    end
    member do
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  # belongs_to :brand_sub
  belongs_to :category
  belongs_to :user
  has_many :likes, dependent: :destroy
  # has_one :tran, dependent: :destroy
  has_many_attached :images
 
  validates :name, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :postage, presence: true
  validates :delivery_method, presence: true
  validates :from_prefecture, presence: true
  validates :delivery_days, presence: true
  validates :price, presence: true


  enum delivery_method: {
    "---":0, "未定":1, "らくらくメルカリ便":2, "ゆうメール":3, "レターパック":4,
    "普通郵便(定形、定形外)":5, "クロネコヤマト":6, "ゆうパック":7,
    "クリックポスト":8, "ゆうパケット":9
  }, _suffix: true

  enum delivery_days: {
    "---":0, "1~2日で発送":1, "2~3日で発送":2, "4~7日で発送":3
  }, _suffix: true

  enum postage: {
    "---":0, "着払い(購入者負担)":1, "送料込み(出品者負担)":2
  }, _suffix: true

  enum condition: {
    "---":0, "新品、未使用":1, "未使用に近い":2, "目立った傷や汚れなし":3,
    "やや傷や汚れあり":4, "傷や汚れあり":5, "全体的に状態が悪い":6
  }, _suffix: true

  enum size: {
    "---":0, "XXS以下":1, "XS(SS)":2, "S":3,
    "M":4, "L":5, "XL(LL)":6, "2XL(3L)":7, "3XL(4L)":8,
    "4XL(5L)以上":8, "FREE SIZE":9
  }, _suffix: true

  enum from_prefecture: {
    "---":0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,未定:48
  }, _suffix: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  require 'payjp'
  before_action :set_item, only: [:show, :purchase1, :edit, :update, :destroy,:pay]

  def index
    @items = Item.where(category: 1..199).where.not(user_id: session[:user_id]).order("created_at DESC").limit(10)
    @vuitton = Item.where(brand: "louis vuitton").where.not(user_id: session[:user_id]).order("created_at DESC").limit(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.images.attached?
      @item.save
      redirect_to root_path
    else
      flash.now[:alert] = "[必須]を入力してください。"
      render "new"
    end
  end

  def category_find
    respond_to do |format|
      parent = Category.find(params[:category_id])
      @children = parent.children
      format.json
    end
  end



  def purchase1
    @item = Item.find(params[:id]) 
    card = Creditcard.where(user_id: @current_user.id).first
    if card.blank?
    else
      Payjp.api_key = "sk_test_5dc292a9b6684847081b4730"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  def pay
    @item = Item.find(params[:id]) 
    card = Creditcard.where(user_id: @current_user.id).first
    Payjp.api_key = 
    "sk_test_5dc292a9b6684847081b4730"
    Payjp::Charge.create(
    :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy', #日本円
  )
  redirect_to done_purchase_path(@current_user.id)
  end

  def show
    @user_items = @item.user.items.order("created_at DESC").limit(6)
    @root = @item.category.root.name
    @parent = @item.category.parent.name
    @children = @item.category.name
    # @price = @item.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse （プライスの表示の仕方その２）
  end

  def edit
  end

  def update
    if @item.images.attached?
      @item.update(item_params)
      redirect_to root_path
    else
      flash.now[:alert] = "[必須]を入力してください。"
      render "edit"
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end



 

  private
  def item_params
    params.require(:item).permit(:name, :description, :category_id, :size, :brand, :condition, :postage, :delivery_method, :from_prefecture, :delivery_days, :price, images: []).merge(user_id: session[:user_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end



end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_exhibit.html.haml
- if session[:user_id]
  .exhibit
    =link_to new_item_path, class: "exhibit__link" do
      .exhibit__link__obj
        .exhibit__link__obj__text
          出品
        .exhibit__link__obj__icon
          = fa_icon 'camera', class: "camera-icon"

- else 
  .exhibit
    =link_to new_user_path, class: "exhibit__link" do
      .exhibit__link__obj
        .exhibit__link__obj__text
          出品
        .exhibit__link__obj__icon
          = fa_icon 'camera', class: "camera-icon"

app/views/items/_footer.html.haml
.footer__top
  .footer__top__menu
    %h2.footer__top__menu__title
      エフマケについて
    %ul.footer__top__menu__list
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          会社概要（運営会社）
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          採用情報
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          プレリリース
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          公式ブログ
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          エフマケロゴ利用ライン
      =link_to "", class: "footer__top__menu__list__link-icon" do
        = fa_icon 'twitter', class: "sns-icon"
      =link_to "", class: "footer__top__menu__list__link-icon" do
        = fa_icon 'facebook-square', class: "sns-icon"
  .footer__top__menu
    %h2.footer__top__menu__title
      ヘルプ＆ガイド
    %ul.footer__top__menu__list
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          エフマケガイド
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          らくらくエフマケ便
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          ゆうゆうエフマケ便
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          大型エフマケ便
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          車体取引ガイド
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          エフマケあんしん・あんぜん宣言！
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          偽ブランド品撲滅への取り組み
      %li.footer__top__menu__list__link
        =link_to "", class: "footer__top__menu__list__link__do" do
          エフマケボックス
  .footer__top__privacy
    %h2.footer__top__privacy__title
      プライバシーと利用規約
    %ul.footer__top__privacy__list
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          プライバシーポリシー
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          エフマケ利用規約
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          あんしんスマホサポート制度に関する利用特約
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          コンプライアンスポリシー
    %ul.footer__top__privacy__list2
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          個人データの安全管理に係る基本方針
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          特定商取引に関する表記
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          資金決済法に基づく表示
      %li.footer__top__privacy__list__link
        =link_to "", class: "footer__top__privacy__list__link__do" do
          法令順守と犯罪抑止のために
  .footer__top__langage
    %h2.footer__top__langage__title
      国
    %ul.footer__top__langage__list
      %li.footer__top__langage__list__link
        =link_to "", class: "footer__top__langage__list__link__do" do
          日本
      %li.footer__top__langage__list__link
        =link_to "", class: "footer__top__langage__list__link__do" do
          United States
.footer__bottom
  =link_to "http://localhost:3000/", class: "footer__bottom__logo" do
    <svg class="footer__bottom__logo__link" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 281.19 84.08"><defs><style>.white-logo{fill:#fff;stroke:#b53d22;stroke-miterlimit:10;}.white-logo-text{font-size:48px;fill:#fff;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}</style></defs><title>アセット 1</title><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><polygon class="white-logo" points="36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"/><polyline class="white-logo" points="0.5 21.31 36.41 42.04 72.32 21.31"/><polyline class="white-logo" points="36.41 83.5 36.41 49.36 36.41 42.04"/><line class="white-logo" x1="36.41" y1="52.41" x2="0.5" y2="31.67"/><line class="white-logo" x1="72.32" y1="33.2" x2="36.41" y2="50.88"/><text class="white-logo-text" transform="translate(86.41 62.77)">Fmarket</text></g></g></svg>
  %a.footer__bottom__copyright
    © 2019 Freemarket

app/views/items/_header.html.haml
.header
  = link_to root_path do
    %h1
      .header__logo <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 281.19 84.08"><defs><style>.cls-1{fill:#dc4912;stroke:#fff;stroke-miterlimit:10;}.cls-2{font-size:48px;fill:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}</style></defs><title>アセット 3</title><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><polygon class="cls-1" points="36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"/><polyline class="cls-1" points="0.5 21.31 36.41 42.04 72.32 21.31"/><polyline class="cls-1" points="36.41 83.5 36.41 49.36 36.41 42.04"/><line class="cls-1" x1="36.41" y1="52.41" x2="0.5" y2="31.67"/><line class="cls-1" x1="72.32" y1="33.2" x2="36.41" y2="50.88"/><text class="cls-2" transform="translate(86.41 62.77)">Fmarket</text></g></g></svg>

app/views/items/_hedder.html.haml
.hedder__menu
  .hedder__menu__top
    .hedder__menu__top__logo
      =link_to root_path, class: "hedder__menu__top__logo__link" do
        <svg class="hedder__menu__top__logo__link__do" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 281.19 84.08"><defs><style>.color-logo{fill:#dc4912;stroke:#fff;stroke-miterlimit:10;}.color-logo-text{font-size:48px;fill:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}</style></defs><title>アセット 3</title><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><polygon class="color-logo" points="36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"/><polyline class="color-logo" points="0.5 21.31 36.41 42.04 72.32 21.31"/><polyline class="color-logo" points="36.41 83.5 36.41 49.36 36.41 42.04"/><line class="color-logo" x1="36.41" y1="52.41" x2="0.5" y2="31.67"/><line class="color-logo" x1="72.32" y1="33.2" x2="36.41" y2="50.88"/><text class="color-logo-text" transform="translate(86.41 62.77)">Fmarket</text></g></g></svg>
    %form#sform.hedder__menu__top__search{action: "", method: "get"}
      %input#sbox.hedder__menu__top__search__input{name: "search", type: "text", placeholder: "何かお探しですか？"}/
      %button#sbtn.hedder__menu__top__search__icon{type: "submit"}
        = fa_icon 'search', class: "search-icon"
  .hedder__menu__bottom
    .hedder__menu__bottom__left
      .hedder__menu__bottom__left__category
        =link_to "", class: "item-link-list" do
          = fa_icon 'list-ul', class: "item-link-logo"
          カテゴリーから探す
      .hedder__menu__bottom__left__brand
        =link_to "", class: "item-link-list" do
          = fa_icon 'shopping-bag', class: "item-link-logo"
          ブランドから探す
   
    -# ログインしている時
    - if session[:user_id]
      .hedder__menu__bottom__right
        .hedder__menu__bottom__right__link
          =link_to "", class: "logined" do
            %i.far.fa-heart.icon
            %p いいね！一覧
        .hedder__menu__bottom__right__link
          =link_to "", class: "logined" do
            %i.far.fa-bell.icon
            %p お知らせ
        .hedder__menu__bottom__right__link
          =link_to "", class: "logined" do
            %i.fas.fa-check.icon
            %p やることリスト
        .hedder__menu__bottom__right__link
          =link_to user_path(id: session[:user_id]), class: "logined" do
            %i.fas.fa-user.icon
            %p マイページ
    
    -# ログインしてない時
    - unless session[:user_id]
      .hedder__menu__bottom__right
        .hedder__menu__bottom__right__entry
          =link_to new_user_path, data: {"turbolinks": false}, class: "new-entry-link" do
            新規会員登録
        .hedder__menu__bottom__right__login
          =link_to login_users_path, data: {"turbolinks": false}, class: "login-link" do
            ログイン
    

app/views/items/edit.html.haml
- if session[:user_id]
  .container-o
    .header-o
      %h1
        = link_to root_path do
          .header__logo <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 281.19 84.08"><defs><style>.cls-1{fill:#dc4912;stroke:#fff;stroke-miterlimit:10;}.cls-2{font-size:48px;fill:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}</style></defs><title>アセット 3</title><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><polygon class="cls-1" points="36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"/><polyline class="cls-1" points="0.5 21.31 36.41 42.04 72.32 21.31"/><polyline class="cls-1" points="36.41 83.5 36.41 49.36 36.41 42.04"/><line class="cls-1" x1="36.41" y1="52.41" x2="0.5" y2="31.67"/><line class="cls-1" x1="72.32" y1="33.2" x2="36.41" y2="50.88"/><text class="cls-2" transform="translate(86.41 62.77)">Fmarket</text></g></g></svg>
    =form_for @item, class: "main" do |f|
      %section.main__container
        #sell-container
          .data-reactroot
            .sell-container
              %h2.sell-container__text 商品の情報を入力
              .sell-form
                .sell-upload-box
                  %span.sell-upload-head 出品画像 
                  %span.form-require 必須
                  %p 最大10枚までアップロードできます
                  .sell-dropbox-container-number10
                    .sell-upload-items-container
                      .items-have-item-0
                      .image_box
                        %ul.sell_image
                          - if @item.images.attached?
                            - @item.images.reverse.each do |image|
                              %li
                                #result
                                  = image_tag image
                                  .image_text
                                    %a.img_edit 編集
                                    %span 
                                      |
                                    %a.img_destroy 削除

                  .sellpage_image_form
                    = f.label :images, multiple: true, class: "dropbox-have-item-0" do
                      = f.file_field :images, multiple: true, class: "hidden"
                      %p.visible-pc ドラッグアンドドロップ  
                      %p.also-visible-pc またはクリックしてファイルファイルをアップロード
                      %i.icon-camera
                
              .sell-content
                .form-group
                  %label 商品名
                  %span 必須
                  .form-name
                    = f.text_field :name, class: "field-name", placeholder: "商品名(必須 40文字まで)"
                .form-group
                  %label 商品の説明
                  %span 必須
                  .form-description
                    = f.text_area :description, class: "field-description", row: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
              
              .sell-details
                %h3.detail-text 商品の詳細
                .sell-form-box
                  .form-group
                    %label カテゴリー
                    %span 必須
                    .category
                      = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: "---"}, class: "select-default", id: "category-select"
                    .select-wrap#child-wrap
                      .category1
                        =f.select :category_id, {}, {}, class: "select-default", id: "child-select" do
                          - if @item.category.present?
                            %option{value: "#{@item.category.parent.id}", class: "child-option"}
                              = @item.category.parent.name
                    .select-wrap#grandchild-wrap
                      .category2
                        =f.select :category_id, {}, {}, class: "select-default", id: "grandchild-select" do
                          - if @item.category.present?
                            %option{value: "#{@item.category.id}", class: "grandchild-option"}
                              = @item.category.name
                  .form-group-size
                    %label サイズ
                    %span 必須
                    .size
                      = f.select :size, Item.sizes.keys
                  .form-group-brand
                    %label ブランド
                    %span.option 任意
                    .brand
                      = f.text_field :brand, placeholder: "例） シャネル", class: "brand-form"
                  .form-group
                    %label 商品の状態
                    %span 必須
                    .detail
                      = f.select :condition, Item.conditions.keys
              
              .sell-delivery
                %h3.delivery-text 配送について
                = link_to "#", class: "question" do
                  = fa_icon "question-circle", class: "icon"
                .delivery-form-box
                  .form-group
                    %label 配送料の負担
                    %span 必須
                    .postage
                      = f.select :postage, Item.postages.keys
                  .after-selected-postage
                    %label 配送の方法
                    %span 必須
                    .delivery-method
                      = f.select :delivery_method, Item.delivery_methods.keys
                  .form-group
                    %label 発送元の地域
                    %span 必須
                    .delivery-region
                      = f.select :from_prefecture, Item.from_prefectures.keys
                  .form-group
                    %label 発送までの日数
                    %span 必須
                    .delivery-days
                      = f.select :delivery_days, Item.delivery_days.keys
              
              .sell-cost
                %h3.cost-text 販売価格(300〜9,999,999)
                = link_to "#", class: "question" do
                  = fa_icon "question-circle", class: "icon"
                .cost-form-box
                  %ul.sell-price
                    %li.form-group
                      .cost-text
                        %label 価格
                        %span 必須
                        .cost 
                          %p ¥
                          .form-cost
                            = f.text_field :price, class: "field-cost", placeholder: "例）300"
                    %li.form-group
                      %p.fee-text 販売手数料(10%)
                      %span.hyphen -
                    %li.form-group
                      %p.profit-text 販売利益
                      %span.hyphen-bold -
              
              .sell-btn
                %p.row
                  %span.blue 禁止されている出品
                  %span 、
                  %span.blue 行為
                  %span を必ずご確認ください。
                %p.row
                  %span またブランド品でシリアルナンバー等がある場合はご記載ください。
                  %span.blue 偽ブランドの販売
                  %span は犯罪であり処罰される可能性があります。
                %p.row
                  %span また、出品をもちまして
                  %span.blue 加盟店規約
                  %span に同意したことになります。
                .submit
                  = f.submit "出品する", class: "submit-btn"
                .back
                  = link_to root_path do
                    %button.back-btn もどる


    .footer-o
      %nav
        %ul.crearfix
          %li
            = link_to "#" do
              プライバシーポリシー
          %li
            = link_to "#" do
              メルカリ利用規約
          %li
            = link_to "#" do
              特定商取引に関する表記
      = link_to "#", class: "footer__logo" do
        .footer--img <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 147.09 129.96"><defs><style>.cls-1,.cls-2{fill:#231815;stroke-miterlimit:10;opacity:0.19;}.cls-1{stroke:#fff;}.cls-2{font-size:36px;stroke:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}</style></defs><title>アセット 13</title><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><polygon class="cls-1" points="71.54 83.5 35.63 62.77 35.63 21.31 71.54 0.58 107.45 21.31 107.45 62.77 71.54 83.5"/><polyline class="cls-1" points="35.63 21.31 71.54 42.04 107.45 21.31"/><polyline class="cls-1" points="71.54 83.5 71.54 49.36 71.54 42.04"/><line class="cls-1" x1="71.54" y1="52.41" x2="35.63" y2="31.67"/><line class="cls-1" x1="107.45" y1="33.2" x2="71.54" y2="50.88"/><text class="cls-2" transform="translate(0.5 117.04)">Fmarket</text></g></g></svg>
      %p
        %small © 2019 Mercari
        

app/views/items/login.html.haml
.container
  = render partial: 'header'

  .main
    .main__no-account
      %p.main__no-account__text
        アカウントをお持ちでない方はこちら
      = link_to '#', {data: {"turbolinks": false}} do
        .main__no-account__btn
          新規会員登録
    .main__sns-login
      = link_to 'Facebook', {data: {"turbolinks": false}} do
        .main__sns-login__facebook
          = icon('fab', 'facebook-square')
          Facebookでログイン
      = link_to 'Google', {data: {"turbolinks": false}} do
        .main__sns-login__google
          = icon('fab', 'google')
          Googleでログイン
    = form_for "#", {html: {class: "main__email-pass-form"}} do |f|
      = f.email_field :email, class: 'main__email-pass-form__email', placeholder: 'メールアドレス'
      = f.password_field :password, class: 'main__email-pass-form__password', placeholder: 'パスワード'
      .main__email-pass-form__login-captcha
      = f.submit 'ログイン', class: 'main__email-pass-form__btn'
      .main__email-pass-form__forgot-password
        パスワードをお忘れの方
        
  = render partial: 'footer'

app/views/items/purchase1.html.haml
= render "header"
.main
  .purchase
    .purchase__title
      購入内容の確認
    .purchase__item
      %figure
        = image_tag @item.images.last , size: "200x200"
        -# - @item.images.first.each do |image|
      .purchase__item-name
        %p 
        = @item.name
      .price
        %p
        = "¥#{@item.price.to_s.gsub(/(\d)(?=(\d{3})+(?!\d))/, '\1,')}"
        %p (送料込み)
      .point2
        %div 
          = link_to "#" do
            ポイントはありません
      .money
        %p 支払金額
        %p 
          = "¥#{@item.price.to_s.gsub(/(\d)(?=(\d{3})+(?!\d))/, '\1,')}"
      - if @default_card_information.blank?
        %h5 配送先と支払方法の入力を完了して下さい
      -else 
        %div 
        = form_tag( pay_item_path, method: :post,class: "point3") do
          %button 購入する
    .delivery
      .delivery__box
        %ul
          %li 配送先
          %li 
            = @current_user.address.post_number
          %li 
            = @current_user.address.prefecture     
            = @current_user.address.city
            = @current_user.address.address
            = @current_user.address.building
          %li 
            = @current_user.last_name
            = @current_user.first_name    
          %li
            = link_to "#" do
              変更する
              = fa_icon 'angle-right'
    .delivery
      .delivery__box
        %ul
          %li 支払方法
          - if @default_card_information.blank?
            %br /
            %li
              = link_to card_creditcard_path(@current_user.id) do
                変更する
                = fa_icon 'angle-right'            
          - else
            -#以下カード情報を表示
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %section
              .cards-list__info
                = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912",width: "49",alt:"visa",height:"15")
            %li
              = link_to card_creditcard_path(@current_user.id) do
                変更する
                = fa_icon 'angle-right'


= render "footer2"
              

app/views/items/registration1.html.haml
.container
  = render partial: 'header'

  .main
    .main__header
      新規会員登録
    .main__how-to-register
      = link_to 'email', {data: {"turbolinks": false}} do
        .main__how-to-register__email
          = icon('far', 'envelope')
          メールアドレスで登録する
      = link_to 'facebook', {data: {"turbolinks": false}} do
        .main__how-to-register__facebook
          = icon('fab', 'facebook-square')
          facebookで登録する
      = link_to 'google', {data: {"turbolinks": false}} do
        .main__how-to-register__google
          = icon('fab', 'google')
          googleで登録する

  = render partial: 'footer'

app/views/items/registration6.html.haml
.container
  = render partial: 'devise/shared/header-with-progress'

  .main
    .main__header6
      会員登録完了
    .main__body
      .main__body__finish-message
        ありがとうございます。会員登録が完了しました。
      = link_to '#', {data: {"turbolinks": false}} do
        .main__body__start-btn
          メルカリをはじめる

  = render partial: 'devise/shared/footer'